In [10]:
import cv2
import mediapipe as mp
import numpy as np
import csv

import os
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd 

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [11]:
mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose

In [ ]:
cap = cv2.VideoCapture (0)
height= cap.get(cv2.CAP_PROP_FRAME_HEIGHT)
width= cap.get(cv2.CAP_PROP_FRAME_WIDTH)
fps = cap.get (cv2.CAP_PROP_FPS)
videoWriter = cv2.VideoWriter('hip_exce.mp4', cv2.VideoWriter_fourcc('P','I', 'M','1'), fps, (int(width), int(height)))
while cap.isOpened():
    ret, frame = cap.read()
    try:
        cv2.imshow('hip_exce', frame)
        videoWriter.write(frame)
    except  Exception as e:
        break
    if cv2.waitKey (10) & 0xFF == ord('q'):
        break
cap.release()
videoWriter.release()
cv2.destroyAllWindows()

In [12]:
landmarks = ['class']
for val in range(1, 33+1):
    landmarks += ['x{}'.format(val), 'y{}'.format(val), 'z{}'.format(val), 'v{}'.format(val)]

In [13]:
with open('feature_hip.csv', mode='w', newline='') as f:
    csv_writer = csv.writer(f, delimiter=',',quotechar='"', quoting=csv.QUOTE_MINIMAL)
    csv_writer.writerow(landmarks)

In [14]:
def export_landmark(results, action):
    try:
        keypoints = [action]  # Initialize the list with the action label

        # Extract pose landmarks and append them to the keypoints list
        for landmark in results.pose_landmarks.landmark:
            keypoints.extend([landmark.x, landmark.y, landmark.z, landmark.visibility])

        # Open the CSV file in 'a' (append) mode and write the keypoints
        with open('feature_hip.csv', mode='a', newline='') as f:
            csv_writer = csv.writer(f, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
            csv_writer.writerow(keypoints)
    except Exception as e:
        print(f"Error in export_landmark: {e}")

In [15]:

# Create a VideoCapture object to open the video file
video_path = 'C:/Projects/FinalProject/excesise_proj/hip_exces/hip_exce.mp4'
cap = cv2.VideoCapture(video_path)

# Check if the video file is opened successfully
if not cap.isOpened():
    print("Error: Could not open video file.")
    exit()

# Initialize a variable to keep track of the current pose
current_pose = None

# Create a dictionary to map keys to pose labels
key_to_pose = {
    ord('z'): 'left',
    ord('x'): 'middle',
    ord('c'): 'right'
}

# Main processing loop
with mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose:
    while cap.isOpened():
        ret, frame = cap.read()

        if not ret:
            break  # Exit the loop when there are no more frames

        # Convert frame to RGB
        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        # Perform pose detection
        results = pose.process(image)

        # Convert back to BGR for rendering
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

        # Draw landmarks and lines on the frame
        mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_pose.POSE_CONNECTIONS,
                                  mp_drawing.DrawingSpec(color=(245, 117, 66), thickness=2, circle_radius=2),
                                  mp_drawing.DrawingSpec(color=(245, 66, 230), thickness=2, circle_radius=2))

        # Check for key presses and export landmarks
        key = cv2.waitKey(1)
        if key in key_to_pose:
            current_pose = key_to_pose[key]
            print(current_pose)
            export_landmark(results, current_pose)

        # Display the frame
        cv2.imshow('webcam feed', image)

        # Check for 'q' key to quit
        if key == ord('q'):
            break

# Release resources
cap.release()
cv2.destroyAllWindows()

left
left
left
left
left
left
left
left
middle
middle
middle
middle
middle
middle
middle
middle
middle
middle
right
right
right
right
right
right
right
right
right
right
right
right
middle
middle
middle
middle
middle
middle
middle
middle
middle
left
left
left
left
left
left
left
middle
middle
middle
middle
middle
middle
middle
middle
right
right
right
right
right
right
right
right
middle
middle
middle
middle
middle
middle
middle
middle
left
left
left
left
left
left
left
left
middle
middle
middle
middle
middle
middle
middle
middle
right
right
right
right
right
right
right
right
middle
middle
middle
middle
middle
middle
middle
middle
middle
middle
left
left
left
left
left
middle
middle
middle
middle
right
right
right
right
right
right
right
middle
middle
middle
middle
middle
middle
middle
middle
middle
left
left
left
left
left
left
left
left
middle
middle
middle
middle
middle
middle
middle
right
right
right
right
right
right
right
right
right
right
middle
middle
middle
middle
middle
midd

In [24]:
df = pd.read_csv('C:/Projects/FinalProject/excesise_proj/hip_exces/feature_hip.csv')

In [25]:
df

class        x1        y1        z1        v1        x2        y2  \
0      left  0.697586  0.202015 -0.291488  0.999743  0.711014  0.188498   
1      left  0.700313  0.212763 -0.267364  0.999734  0.713851  0.200026   
2      left  0.699911  0.218641 -0.251038  0.999776  0.714608  0.205642   
3      left  0.698789  0.220022 -0.346584  0.999746  0.713922  0.206346   
4      left  0.698451  0.218172 -0.211541  0.999764  0.713785  0.205286   
..      ...       ...       ...       ...       ...       ...       ...   
245   right  0.553097  0.190940 -0.331994  0.999059  0.558151  0.167119   
246  middle  0.639100  0.139334 -0.364035  0.999704  0.649720  0.121151   
247  middle  0.652797  0.139895 -0.458592  0.999774  0.663193  0.121595   
248  middle  0.663430  0.141699 -0.356074  0.999841  0.674737  0.123683   
249  middle  0.667950  0.141523 -0.447254  0.999875  0.677741  0.122888   

           z2        v2        x3  ...       z31       v31       x32  \
0   -0.276844  0.999400  0.716015  ...  0.074393  0.345099  0.654236   
1   -0.248499  0.999331  0.718650  ...  0.110550  0.303172  0.633989   
2   -0.239540  0.999375  0.719595  ...  0.105238  0.289664  0.635036   
3   -0.328977  0.999289  0.718673  ...  0.122416  0.286131  0.628870   
4   -0.196560  0.999311  0.718537  ...  0.061895  0.274552  0.649594   
..        ...       ...       ...  ...       ...       ...       ...   
245 -0.317493  0.997856  0.564445  ...  0.184613  0.309200  0.669352   
246 -0.349573  0.999326  0.655294  ...  0.194801  0.411987  0.649962   
247 -0.435217  0.999488  0.668914  ...  0.450949  0.403292  0.653974   
248 -0.341968  0.999642  0.680368  ...  0.245437  0.428350  0.643374   
249 -0.430193  0.999720  0.682742  ...  0.324611  0.418343  0.653459   

          y32       z32       v32       x33       y33       z33       v33  
0    1.068649  0.015522  0.598960  0.566306  1.054807 -0.064071  0.482837  
1    1.054987  0.069269  0.488723  0.541746  1.045021 -0.019597  0.435924  
2    1.061130  0.021545  0.439297  0.531101  1.054122 -0.007660  0.420576  
3    1.064060 -0.020776  0.421261  0.527856  1.049788 -0.022094  0.405144  
4    1.065395 -0.047247  0.405906  0.552546  1.059146 -0.045416  0.392795  
..        ...       ...       ...       ...       ...       ...       ...  
245  1.039956 -0.077482  0.431181  0.572456  0.967310  0.075334  0.354409  
246  1.030603 -0.017484  0.585173  0.580639  1.003751  0.079024  0.497868  
247  1.059199 -0.098206  0.601387  0.577482  0.975660  0.338531  0.486546  
248  1.049528 -0.088726  0.632919  0.568869  0.966459  0.138920  0.523990  
249  1.048300 -0.112294  0.625619  0.580229  0.941212  0.199305  0.500581  

[250 rows x 133 columns]

In [26]:
x = df.drop('class', axis=1)
y=df['class']

In [27]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=1234)

In [28]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=3)

model.fit(x_train, y_train)


KNeighborsClassifier(n_neighbors=3)

In [31]:
import pickle
# Save the model to a file

model_file = 'C:/Projects/FinalProject/excesise_proj/hip_exces/hip_exces_latest.pkl'
with open(model_file, 'wb') as file:
    pickle.dump(model, file)
print(f"Model saved as {model_file}")

Model saved as C:/Users/shana/OneDrive/Desktop/excesise_proj/hip_exces/hip_exces_latest.pkl


In [29]:
y_pred = model.predict(x_test)

In [30]:
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.99
              precision    recall  f1-score   support

        left       1.00      0.96      0.98        24
      middle       0.97      1.00      0.98        31
       right       1.00      1.00      1.00        20

    accuracy                           0.99        75
   macro avg       0.99      0.99      0.99        75
weighted avg       0.99      0.99      0.99        75

[[23  1  0]
 [ 0 31  0]
 [ 0  0 20]]


In [6]:
import pickle
model_hip_exce = 'C:/Projects/FinalProject/excesise_proj/hip_exces/hip_exce.pkl'
model_hip_on = 'C:/Projects/FinalProject/excesise_proj/hand_on_hip/hand_on_hip.pkl'
model_filename = 'C:/Projects/FinalProject/excesise_proj/leg_exces/leg_position.pkl'

with open(model_hip_exce, 'rb') as file:
    model_hip_exce = pickle.load(file)

with open(model_hip_on, 'rb') as file:
    model_hip_on = pickle.load(file)

with open(model_filename, 'rb') as file:
    leg_pos = pickle.load(file)

In [7]:


# Initialize MediaPipe
mp_pose = mp.solutions.pose
mp_drawing = mp.solutions.drawing_utils

# Initialize variables
cap = cv2.VideoCapture(0)
count = 0

state1 =''
state2=''
state3 = 'midle'

class_to_action = {
    'nutral': 'nutral',
    'mid': 'mid',
    'wide': 'wide'
}

with mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose:
    while cap.isOpened():
        ret, frame = cap.read()

        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        image.flags.writeable = False

        # Make detection
        results = pose.process(image)

        # Recolor back to BGR
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

        mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_pose.POSE_CONNECTIONS,
                                  mp_drawing.DrawingSpec(color=(245, 117, 66), thickness=2, circle_radius=2),
                                  mp_drawing.DrawingSpec(color=(245, 66, 230), thickness=2, circle_radius=2))

        try:
            row = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten().tolist()
            x = pd.DataFrame([row], columns=landmarks[1:])
            hip_on_class = model_hip_on.predict(x)[0]
            hip_on_prob = model_hip_on.predict_proba(x)[0]

            state_class = model_hip_exce.predict(x)[0]
            state_prob = model_hip_exce.predict_proba(x)[0]

            leg_class = leg_pos.predict(x)[0]
            leg_prob = leg_pos.predict_proba(x)[0]
            #print(f"State: {state}, State Class: {state_class}, State Prob: {state_prob}, Count: {count}")

            if leg_class in class_to_action and leg_prob[leg_prob.argmax()] >= 0.7:
                state1 = class_to_action[leg_class]

            if leg_class == 'mid':
                cv2.putText(image, 'Keep your legs in distance', (10, 280), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 2, cv2.LINE_AA)



            if hip_on_class == 'on' and hip_on_prob[hip_on_prob.argmax()] >= 0.7:
                state2 = 'on'
            elif state2 == 'on' and hip_on_class == 'off' and hip_on_prob[hip_on_prob.argmax()] >= 0.7:
                state2 = 'off'
            if hip_on_class == 'off' and hip_on_prob[hip_on_prob.argmax()] >= 0.7:
                cv2.putText(image, 'Keep your hand on hip', (10, 200), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2, cv2.LINE_AA)


            if state_class == 'left' and state_prob[state_prob.argmax()] >= 0.7:
                state3 = 'left'
            elif state3 == 'left' and state_class == 'midle' and state_prob[state_prob.argmax()] >= 0.7:
                state3 = 'midle'
                count += 1
            elif state3 == 'midle' and state_class == 'right' and state_prob[state_prob.argmax()] >= 0.7:
                state3 = 'right'
            


            
            cv2.rectangle(image, (0, 0), (200, 40), (245, 117, 16), -1)  # First rectangle

            cv2.putText(image, 'HIP CLASS', (55, 12), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1, cv2.LINE_AA)

            cv2.putText(image, state_class.split(' ')[0], (50, 35), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 255, 255), 2, cv2.LINE_AA)

            cv2.rectangle(image, (220, 0), (380, 40), (16, 117, 245), -1)  # Second rectangle

            cv2.putText(image, 'HAND ON HIP', (275, 12), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1, cv2.LINE_AA)

            cv2.putText(image, hip_on_class.split(' ')[0], (270, 35), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 255, 255), 2, cv2.LINE_AA)

            cv2.rectangle(image, (400, 0), (560, 40), (0, 255, 0), -1)  # Third rectangle

            cv2.putText(image, 'LEG POS', (455, 12), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1, cv2.LINE_AA)

            cv2.putText(image, leg_class.split(' ')[0], (450, 35), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 255, 255), 2, cv2.LINE_AA)

        except Exception as e:
            print(f"Error: {e}")

        cv2.imshow('webcam feed', image)

        if cv2.waitKey(10) & 0xFF == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()


In [ ]:
#import joblib
#joblib.dump(model, 'hip_exce.pkl')

In [ ]:
#model = joblib.load('C:/Projects/FinalProject/excesise_proj/hip_exces/hip_exce.pkl')